### ISSUE TITLE
dsm (Gomex dolphins) with R 3.4.0

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsm#30] opened 2017-04-25 14:46 UTC
* The vignette on distancesampling.org `attach()` following `data(mexdolphins)` even though recent versions of dsm() state this is not necessary
* warning messages issued when calling `summary()` with an object of class `dsmodel`

```
Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
```
* somewhat scarier issues when running `dsm()`

```
dsm.xy <- dsm(count~s(x,y), detfc.hr.null, segdata, obsdata, method="REML")
Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots) : object 'C_construct_tprs' not found
```

afraid that error puts and stop to my continued investigation as subsequent code depends upon existence of dsm object

Note, my machine has come down with a series of maladies since installing R 3.4.0; it required a new version of R-Studio and even with this, refuses to install.packages() because of equally exotic error messages:

```
install.packages("babar")
Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed
```

**Comment by dill** [comment] 2017-04-25 21:22
In order:

- there is an updated version of the vignette which solves this issue at [https://github.com/dill/mexico-data](https://github.com/dill/mexico-data) which Laura and I were going to upload once the new `dsm` is on CRAN.
- urgh, this is annoying as I use this trick in a few places to avoid typing. I can't reproduce as my (old) version of OS X is incompatible with R 3.4 But this looks like a `Distance` issue not `dsm`? Can you produce a minimal example and post to the issues there?
- No idea what's happening there but perhaps requires a re-install of `mgcv`?

No idea what's happening with that last `install.packages()` issue.

**Comment by LHMarshall** [comment] 2017-04-25 22:14
sounds like we should stick with R3.3 for now!

**Comment by LHMarshall** [comment] 2017-04-25 22:15
eugh guess to do CRAN release we need to pass ckecks on it though :(

**Comment by erex** [comment] 2017-04-26 07:50
I was sticking my toe in the water of R 3.4.0 because the intention was to release D7.1 after R 3.4.0 was released.  I didn't do comprehensive testing; what is the plan?

**Comment by lenthomas** [comment] 2017-04-26 07:57
Hmm, I'd far rather release a Distance 7.1 that is compatible with R3.4 than have it only comptible with an out-of-date version of R on release.  Eric, would you have time to produce a minimal example illustrating the problem you found with dsm/distance?  Dave, would you have time to fix it?

**Comment by erex** [comment] 2017-04-26 08:04
I'll investigate; first I need to understand why my install of R3.4.0 is such a mess.  Thereafter, I'll investigate `ds()` in Distance, then on to `dsm()` in `dsm`.  Investigation ceased yesterday when I could not create a `dsm` object, so I could not investigate further.

**Comment by erex** [comment] 2017-04-26 09:02
Minimal example for issues generated by `ds()` under R3.4.0 [located here](https://github.com/DistanceDevelopment/Distance/issues/17)

**Comment by erex** [comment] 2017-04-26 10:11
### Trace of errors generated by `dsm()` on Gomex example

[Call in `dsm()`](https://github.com/DistanceDevelopment/dsm/blob/master/R/dsm.R#L175)
  fit <- withCallingHandlers(do.call(engine, args), warning = matrixnotposdef.handler)

causes
```
debug: fit <- withCallingHandlers(do.call(engine, args), warning = matrixnotposdef.handler)
Browse[2]> n
Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots) : 
  object 'C_construct_tprs' not found
```

Rooting about inside `smooth.construct.tp.smooth.spec()` is found the line

```
    oo <- .C(C_construct_tprs, as.double(x), as.integer(object$dim), 
        as.integer(n), as.double(knt), as.integer(nk), as.integer(object$p.order[1]), 
        as.integer(object$bs.dim), X = as.double(X), S = as.double(S), 
        UZ = as.double(UZ), Xu = as.double(Xu), n.Xu = as.integer(nXu), 
        C = as.double(C))
```
and the first argument in the `.C()` call appears to be the missing object

version of mgcv in use is 1.8-17

That's as far as I can trace because no `dsm()` object can be created.  End of the trail.

**Comment by LHMarshall** [comment] 2017-04-26 12:21
@lenthomas yes me too but I have the same issue as Dave I cannot currently run R 3.4 on my machine my operating system is too old. I suspect to release with R 3.4 is going to cause significant delays. I wonder how many others will have issues with it an not want to upgrade straight away any way.

**Comment by dill** [comment] 2017-04-26 14:19
I will try to fix Eric's problems on my machine as-is. I can't do the 
upgrade and test etc until after IWC as I don't want to break my 
computer before I give that workshop.

One option would be to put R 3.4 on isbjorn and test there?

**Comment by erex** [comment] 2017-04-26 14:22
Issues reconciled.  Re-installed packages `mgcv`, `nlme` and `lme4` because of C compiler error messages thrown.

**Vignette now runs to completion** (with added warning messages about recycling added for free).  I stopped most of them coming from `summary()` but some still leak out from `ddf.gof()` and `dsm.var.prop()`

**Comment by dill** [comment] 2017-04-26 14:35
@erex: great!

Can we:

1. Close this issue?
2. I'll take a look at the outstanding `Distance` issue (which is actually an `mrds` issue)?
3. Open new issues for any non-`mrds` issues with `dsm.var.prop`?

**Comment by erex** [comment] 2017-04-26 14:36
### New issue with `dsm_varprop()`
(I should start a new issue, but keeping this one alive)

Trying to run Gui's point transect dsm(); all goes well (after `mgcv()` hassle resolved, however, he uses the variance propagation method of computation and this `stop()` message is issued by `dsm_varprop()`

```
Only line transects are supported at the moment
```
Gui however, sent a completed analysis because he was using an earlier version of `dsm()` that did not have that error message.  My uneducated examination of Gui's variance estimate using count as a response looks reasonable.

**Comment by dill** [comment] 2017-04-26 14:38
This error is currently correct as I've not thought deeply about whether 
points are fine w/ dsm.var.prop (intuition says yes).

Please do add a new issue for this and I'll look into it.

**Comment by LHMarshall** [comment] 2017-04-26 14:43
On the plus side R 3.4 runs in XP so I have it installed in the VM... unfortunately I have never managed to get the VM working correctly to complete all the R checks and also the previous version of R studio would not work in XP correctly.

**Closed** 2017-04-26 14:49 UTC

**Comment by erex** [comment] 2017-04-27 08:47
News for R 3.4.0  
* Packages which register native routines for .C or .Fortran need to be re-installed for this version (unless installed with R-devel SVN revision r72375 or later). 
* When we've e-talked about the issue within R-core, Uwe Ligges noted we should really ask everyone to run

```
     update.packages(checkBuilt=TRUE) 
```

**Comment by dill** [comment] 2017-04-27 12:49
Is this advice from Uwe already in the manual? If not it should be added.
